#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          centerMotor,   tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

		if(getColorName(colorSensor)==colorWhite)
		{
			setMotorSpeed(rightMotor, 10);

			setMotorSpeed(leftMotor, 10);
		}
		else
		{

			setMotorSpeed(rightMotor, 0);

			setMotorSpeed(leftMotor, 0);
		}
	}
}
