#pragma config(Sensor, S4,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if (getColorName(colorSensor)==colorWhite)
		{
			motor(leftMotor)=20;
			motor(rightMotor)=20;
		}
		else
		{
			motor(leftMotor)=0;
			motor(rightMotor)=0;
		}
	}
}
