#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
	{
		if(getColorName(S1)==colorBlack)
		{
			setMotorSpeed(rightMotor, 20);

			setMotorSpeed(leftMotor, 20);
		}
		else
		{

			setMotorSpeed(rightMotor, 0);

			setMotorSpeed(leftMotor, 0);
		}
	}
}
