#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          centerMotor,   tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

		if(getColorName(colorSensor)==colorWhite)
		{
			setMotorSpeed(rightMotor, 10);

			setMotorSpeed(leftMotor, 10);
		}
		else
		{
			//turning with 2 wheels
			//phase 1: turn right
			motor(leftMotor)=30;
			motor(rightMotor)=15;
			wait1Msec(1000);
			//phase 2: make a curve
			motor(leftMotor)=15;
			motor(rightMotor)=30;
			wait1Msec(2100);
			//phase 3: second turn to the first shape
			motor(leftMotor)=30;
			motor(rightMotor)=15;
			wait1Msec(1000);
		}
	}
}
